# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc362c3811b0026df9ad8b3a70127efc105d662107e235879962b869e32fcd45c76b2d6bc2fdc0d84f49deb83877de64df0a61a814375b95eabebbf1568a081e

test:
  secret_key_base: ccc5b461f0260806df1a2ab2dc14c3963f6c51a6cd30dcd55fede74073886a47c20f069f4aec3aeebddbeead104a7911afaba11eb13df2f89d111d4e7fe0f986

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
